# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_playground',
                'doc_host': 'https://lobrien.github.io',
                'git_url': 'https://github.com/lobrien/nbdev_playground',
                'lib_path': 'nbdev_playground'},
  'syms': {'nbdev_playground.core': {'nbdev_playground.core.foo': ('core.html#foo', 'nbdev_playground/core.py')}}}